# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(default='', max_length=60)),
                ('app_name', models.CharField(max_length=60)),
                ('cpu_use', models.IntegerField(default=0)),
                ('memory_use', models.IntegerField(default=0)),
                ('disk_use', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemorySpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.App')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=5000)),
                ('list_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.App')),
            ],
        ),
    ]
