# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=60)),
                ('cpu_use', models.DecimalField(decimal_places=2, max_digits=5)),
                ('memory_use', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disk_use', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
