# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
