# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
