# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_processlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorytable',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
