# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_app_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='cpu_use',
        ),
        migrations.RemoveField(
            model_name='app',
            name='disk_use',
        ),
        migrations.RemoveField(
            model_name='app',
            name='memory_use',
        ),
    ]
