# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160817_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='cpu_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='disk_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='memory_use',
            field=models.IntegerField(default=0),
        ),
    ]
