# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_memorytable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='disk_position',
            field=models.IntegerField(default=0),
        ),
    ]
