# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160817_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.App', unique=True)),
            ],
        ),
    ]
