# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_processlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlist',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.App'),
        ),
    ]
